BloggerBlogBundle:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /
BloggerAdminBundle:
    resource: "@BloggerAdminBundle/Resources/config/routing.yml"
    prefix:   /

