BloggerBlogBundle:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /
BloggerAdminBundle:
    resource: "@BloggerAdminBundle/Resources/config/routing.yml"
    prefix:   /backend

login:
    path:   /login
    defaults:  { _controller: BloggerAdminBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path: /logout
register:
    path: /register
    defaults:  { _controller: BloggerAdminBundle:Security:register }
