# app/config/security.yml
security:
    encoders:
        Blogger\BlogBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: BloggerBlogBundle:User, property: username }

    firewalls:
        login_firewall:
             pattern:    ^/login$
             anonymous:  ~
        secured_area:
             pattern:    ^/
             form_login: ~

    access_control:
        - { path: ^/backend/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/backend, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }