# app/config/security.yml
security:
    encoders:
        Blogger\BlogBundle\Entity\User:
            id: blogger.blog.sha256salted_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_USER ]

    providers:
        administrators:
            entity: { class: BloggerBlogBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/backend/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/backend, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }