BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

BloggerBlogBundle_category:
    pattern:  /category/{slug}
    defaults: { _controller: BloggerBlogBundle:Page:category }
    requirements:
        _method:  GET

BloggerBlogBundle_tag:
    pattern:  /tag/{slug}
    defaults: { _controller: BloggerBlogBundle:Page:tag }
    requirements:
        _method:  GET

BloggerBlogBundle_comment_create:
    pattern:  /comment/{blogId}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blogId: \d+