BloggerAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerAdminBundle:Default:index }

############### posts
BloggerAdminBundle_post_edit:
    pattern:  /edit/post/{postId}
    defaults: { _controller: BloggerAdminBundle:Post:editPost }
    requirements:
        _method:  GET|POST
        postId: \d+

BloggerAdminBundle_post_delete:
    pattern:  /delete/post/{postId}
    defaults: { _controller: BloggerAdminBundle:Post:delete }
    requirements:
        _method:  GET
        postId: \d+

BloggerAdminBundle_post_create:
    pattern:  /create-post
    defaults: { _controller: BloggerAdminBundle:Post:create }
    requirements:
        _method:  GET|POST

BloggerAdminBundle_post_submitEdition:
    pattern:  /edit-post/{postId}
    defaults: { _controller: BloggerAdminBundle:Post:submitEdition }
    requirements:
        _method:  GET|POST
        postId: \d+

BloggerAdminBundle_post_new:
    pattern:  /new-post
    defaults: { _controller: BloggerAdminBundle:Post:newPost }
    requirements:
        _method:  GET
############# end of posts


############## categories
BloggerAdminBundle_category_edit:
    pattern:  /edit/category/{catId}
    defaults: { _controller: BloggerAdminBundle:Category:editCategory }
    requirements:
        _method:  GET|POST
        catId: \d+

BloggerAdminBundle_category_delete:
    pattern:  /delete/category/{catId}
    defaults: { _controller: BloggerAdminBundle:Category:delete }
    requirements:
        _method:  GET
        catId: \d+

BloggerAdminBundle_category_create:
    pattern:  /create-category
    defaults: { _controller: BloggerAdminBundle:Category:create }
    requirements:
        _method:  GET|POST

BloggerAdminBundle_category_submitEdition:
    pattern:  /edit-category/{catId}
    defaults: { _controller: BloggerAdminBundle:Category:submitEdition }
    requirements:
        _method:  GET|POST
        catId: \d+

BloggerAdminBundle_category_new:
    pattern:  /new-category
    defaults: { _controller: BloggerAdminBundle:Category:newCategory }
    requirements:
        _method:  GET

BloggerAdminBundle_default_categories:
    pattern:  /categories
    defaults: { _controller: BloggerAdminBundle:Default:categories }
    requirements:
            _method:  GET
############## end of categories

############## tags
BloggerAdminBundle_tag_edit:
    pattern:  /edit/tag/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:editTag }
    requirements:
        _method:  GET|POST
        tagId: \d+

BloggerAdminBundle_tag_delete:
    pattern:  /delete/tag/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:delete }
    requirements:
        _method:  GET
        tagId: \d+

BloggerAdminBundle_tag_create:
    pattern:  /create-tag
    defaults: { _controller: BloggerAdminBundle:Tag:create }
    requirements:
        _method:  GET|POST

BloggerAdminBundle_tag_submitEdition:
    pattern:  /edit-tag/{tagId}
    defaults: { _controller: BloggerAdminBundle:Tag:submitEdition }
    requirements:
        _method:  GET|POST
        tagId: \d+

BloggerAdminBundle_tag_new:
    pattern:  /new-tag
    defaults: { _controller: BloggerAdminBundle:Tag:newTag }
    requirements:
        _method:  GET

BloggerAdminBundle_default_tags:
    pattern:  /tags
    defaults: { _controller: BloggerAdminBundle:Default:tags }
    requirements:
            _method:  GET
############## end of tags