BloggerAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerAdminBundle:Default:index }

BloggerAdminBundle_blog_edit:
    pattern:  /edit/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Blog:editBlog }
    requirements:
        _method:  GET|POST
        blog_id: \d+

BloggerAdminBundle_blog_delete:
    pattern:  /delete/{blog_id}
    defaults: { _controller: BloggerAdminBundle:Blog:delete }
    requirements:
        _method:  GET
        blog_id: \d+

BloggerAdminBundle_blog_submit:
    pattern:  /sumbit-blog
    defaults: { _controller: BloggerAdminBundle:Blog:submit }
    requirements:
        _method:  GET|POST

BloggerAdminBundle_blog_new:
    pattern:  /new-blog
    defaults: { _controller: BloggerAdminBundle:Blog:newBlog }
    requirements:
        _method:  GET