<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getLatestBlogs($posted = true, $limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b', 'c', 't', 'cat')
            ->leftJoin('b.comments', 'c')
            ->leftJoin('b.tags', 't')
            ->leftJoin('b.category', 'cat')
            ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);
        if ($posted === false)
            $qb->where('b.posted = :posted')
                ->setParameter('posted', true);

        return $qb->getQuery()
            ->getResult();
    }

    public function getBlogsInCategory($catId) {
        $em = $this->getEntityManager();
        $categories = $em->getRepository('BloggerBlogBundle:Category')->getChildCategories($catId);

        $qb = $this->createQueryBuilder('b')
            ->select('b', 'c', 't', 'cat')
            ->leftJoin('b.comments', 'c')
            ->leftJoin('b.tags', 't')
            ->leftJoin('b.category', 'cat')
            ->where('b.category IN (:ids)')
            ->setParameter('ids', $categories)
            ->addOrderBy('b.created', 'DESC');

        $qb->andWhere('b.posted = :posted')
            ->setParameter('posted', true);

        return $qb->getQuery()
            ->getResult();
    }

    public function getBlogsOnTag($tagId) {
        $qb = $this->createQueryBuilder('b')
            ->select('b', 'c', 't', 'cat')
            ->leftJoin('b.comments', 'c')
            ->leftJoin('b.tags', 't')
            ->leftJoin('b.category', 'cat')
            ->where('t.id = :id')
            ->setParameter('id', $tagId)
            ->addOrderBy('b.created', 'DESC');

        $qb->andWhere('b.posted = :posted')
            ->setParameter('posted', true);

        return $qb->getQuery()
            ->getResult();
    }

    public function getBlogCountInCategory($category) {
        $em = $this->getEntityManager();
        $categoryRepository = $em->getRepository('BloggerBlogBundle:Category');

        $categoryList = $categoryRepository->findChildren($category);

        $qb = $this->createQueryBuilder('b')
            ->select('count(b)')
            ->innerJoin('b.category', 'c')
            ->where('b.category IN (:ids)')
            ->andWhere('b.posted = 1')
            ->setParameter('ids', $categoryList);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
