<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesList()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c, b')
            ->leftJoin('c.blogs', 'b')
            ->addOrderBy('c.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }
}