<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagList()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t, b')
            ->leftJoin('t.blogs', 'b')
            ->addOrderBy('t.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }
}