<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagList()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t, b')
            ->leftJoin('t.blogs', 'b')
            ->addOrderBy('t.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function isTagUnique($name, $slug) {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.slug = :slug')
            ->orWhere('t.name = :name')
            ->setParameters(
                array(
                    'slug' => $slug,
                    'name' => $name
                )
            );
        if($qb->getQuery()->getResult())
            return false;
        else
            return true;
    }
}